# Generated by Django 5.1 on 2024-08-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_convidados', models.CharField(max_length=30)),
                ('local', models.CharField(max_length=100)),
            ],
        ),
    ]
