# Generated by Django 4.2.15 on 2024-08-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data',
            field=models.DateField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='hora',
            field=models.TimeField(default=2, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
