# Generated by Django 4.2.15 on 2024-08-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='evento',
        ),
    ]
