# Generated by Django 4.2.15 on 2024-08-20 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lista', '0002_delete_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True, default='DD-MM-YYYY', null=True)),
                ('hora', models.TimeField(blank=True, default=datetime.time(9, 0), null=True)),
                ('numero_convidados', models.CharField(max_length=30)),
                ('local', models.CharField(max_length=100)),
            ],
        ),
    ]
