# Generated by Django 4.2.15 on 2024-08-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_evento_data_evento_hora_evento_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.TimeField(),
        ),
    ]
