# Generated by Django 4.2.15 on 2024-08-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_alter_evento_data_alter_evento_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='hora',
        ),
    ]
