# Generated by Django 4.2.15 on 2024-08-20 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0004_remove_evento_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data',
            new_name='data2',
        ),
    ]
