# Generated by Django 4.2.15 on 2024-08-20 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0005_rename_data_evento_data2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='data2',
        ),
    ]
